# Generated by Django 4.0.2 on 2022-02-25 06:11

# import email
from django.db import migrations
from api.user.models import CustomUser


class Migration(migrations.Migration):
    def seed_data(apps, schema_editor):
        user = CustomUser(name="vinay", email="vinspace.89@gmail.com",
                          is_staff=True, is_superuser=True, phone='9604871195', gender='Male')
        user.set_password('123456')
        user.save()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
